# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.distance <- function(sequence1, sequence2, metric, cost_sub, cost_indel) {
    .Call(`_DNABarcodesLigth_distance`, sequence1, sequence2, metric, cost_sub, cost_indel)
}

rcpp_hello_world <- function() {
    .Call(`_DNABarcodesLigth_rcpp_hello_world`)
}

